import type { Metadata } from "next";
import localFont from "next/font/local";
import { AppHeader } from "./components/app-header";

import "@repo/shadcn/globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Next monorepo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex flex-col min-h-dvh">
          <AppHeader />
          <main className="flex-1 m-2 rounded-lg border">
            <div className="container">{children}</div>
          </main>
        </div>
      </body>
    </html>
  );
}
